Entity/Ticket.php
<?php

namespace Hackzilla\Bundle\TicketBundle\Entity;

use Hackzilla\Bundle\TicketBundle\Entity\Traits\TicketTrait;
use Hackzilla\Bundle\TicketBundle\Model\TicketInterface;

/**
 * Ticket.
 */
class Ticket implements TicketInterface
{
    use TicketTrait;

    /**
     * @var int
     */
    protected $id;

    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
}

Entity/Traits/TicketTrait.php
<?php

namespace Hackzilla\Bundle\TicketBundle\Entity\Traits;

use Doctrine\Common\Collections\ArrayCollection;
use Hackzilla\Bundle\TicketBundle\Model\TicketMessageInterface;
use Hackzilla\Bundle\TicketBundle\Model\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Ticket Trait.
 */
trait TicketTrait
{
    /**
     * @var int
     */
    protected $userCreated;
    protected $userCreatedObject;

    /**
     * @var int
     */
    protected $lastUser;
    protected $lastUserObject;

    /**
     * @var \DateTime
     */
    protected $lastMessage;

    /**
     * @Assert\NotBlank()
     *
     * @var string
     */
    protected $subject;

    /**
     * @var int
     */
    protected $status;

    /**
     * @var int
     */
    protected $priority;


    /**
     * @Assert\Count(min = "1")
     * @Assert\Valid()
     *
     * @var ArrayCollection
     */
    protected $messages;

    /**
     * @var \DateTime
     */
    protected $createdAt;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->messages = new ArrayCollection();
    }

    /**
     * Set status.
     *
     * @param int $status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Set status string.
     *
     * @param string $status
     *
     * @return $this
     */
    public function setStatusString($status)
    {
        $status = \array_search(\strtolower($status), TicketMessageInterface::STATUSES);

        if ($status > 0) {
            $this->setStatus($status);
        }

        return $this;
    }

    /**
     * Get status.
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Get status string.
     *
     * @return string
     */
    public function getStatusString()
    {
        if (array_key_exists($this->status, TicketMessageInterface::STATUSES)) {
            return TicketMessageInterface::STATUSES[$this->status];
        }

        return TicketMessageInterface::STATUSES[0];
    }

    /**
     * Set priority.
     *
     * @param int $priority
     *
     * @return $this
     */
    public function setPriority($priority)
    {
        $this->priority = $priority;

        return $this;
    }

    /**
     * Set priority string.
     *
     * @param string $priority
     *
     * @return $this
     */
    public function setPriorityString($priority)
    {
        $priority = \array_search(\strtolower($priority), TicketMessageInterface::PRIORITIES);

        if ($priority > 0) {
            $this->setPriority($priority);
        }

        return $this;
    }

    /**
     * Get priority.
     *
     * @return int
     */
    public function getPriority()
    {
        return $this->priority;
    }

    /**
     * Get priority string.
     *
     * @return string
     */
    public function getPriorityString()
    {
        if (array_key_exists($this->priority, TicketMessageInterface::PRIORITIES)) {
            return TicketMessageInterface::PRIORITIES[$this->priority];
        }

        return TicketMessageInterface::PRIORITIES[0];
    }

    /**
     * Set userCreated.
     *
     * @param int|object $userCreated
     *
     * @return $this
     */
    public function setUserCreated($userCreated)
    {
        if (\is_object($userCreated)) {
            $this->userCreatedObject = $userCreated;
            $this->userCreated = $userCreated->getId();
        } else {
            $this->userCreatedObject = null;
            $this->userCreated = $userCreated;
        }

        return $this;
    }

    /**
     * Get userCreated.
     *
     * @return int
     */
    public function getUserCreated()
    {
        return $this->userCreated;
    }

    /**
     * Get userCreated object.
     *
     * @return object
     */
    public function getUserCreatedObject()
    {
        return $this->userCreatedObject;
    }

    /**
     * Set lastUser.
     *
     * @param int|object $lastUser
     *
     * @return $this
     */
    public function setLastUser($lastUser)
    {
        if (\is_object($lastUser)) {
            $this->lastUserObject = $lastUser;
            $this->lastUser = $lastUser->getId();
        } else {
            $this->lastUserObject = null;
            $this->lastUser = $lastUser;
        }

        return $this;
    }

    /**
     * Get lastUser.
     *
     * @return int
     */
    public function getLastUser()
    {
        return $this->lastUser;
    }

    /**
     * Get lastUser object.
     *
     * @return UserInterface
     */
    public function getLastUserObject()
    {
        return $this->lastUserObject;
    }

    /**
     * Set lastMessage.
     *
     * @param \DateTime $lastMessage
     *
     * @return $this
     */
    public function setLastMessage($lastMessage)
    {
        $this->lastMessage = $lastMessage;

        return $this;
    }

    /**
     * Get lastMessage.
     *
     * @return \DateTime
     */
    public function getLastMessage()
    {
        return $this->lastMessage;
    }

    /**
     * Set createdAt.
     *
     * @param \DateTime $createdAt
     *
     * @return $this
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set subject.
     *
     * @param string $subject
     *
     * @return $this
     */
    public function setSubject($subject)
    {
        $this->subject = $subject;

        return $this;
    }

    /**
     * Get subject.
     *
     * @return string
     */
    public function getSubject()
    {
        return $this->subject;
    }

    /**
     * Add message.
     *
     * @param TicketMessageInterface $message
     *
     * @return $this
     */
    public function addMessage(TicketMessageInterface $message)
    {
        $this->messages[] = $message;

        return $this;
    }

    /**
     * Remove message.
     *
     * @param TicketMessageInterface $message
     *
     * @return $this
     */
    public function removeMessage(TicketMessageInterface $message)
    {
        $this->messages->removeElement($message);

        return $this;
    }

    /**
     * Get messages.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMessages()
    {
        return $this->messages;
    }
}

Form/Type/TicketType.php
<?php

namespace Hackzilla\Bundle\TicketBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TicketType extends AbstractType
{
    protected $ticketClass;

    public function __construct($ticketClass)
    {
        $this->ticketClass = $ticketClass;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'subject',
                TextType::class,
                [
                    'label' => 'LABEL_SUBJECT',
                ]
            )
            ->add(
                'messages',
                CollectionType::class,
                [
                    'entry_type'    => TicketMessageType::class,
                    'entry_options' => [
                        'new_ticket' => true,
                    ],
                    'label'         => false,
                    'allow_add'     => true,
                ]
            );
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => $this->ticketClass,
            ]
        );
    }

    public function getBlockPrefix()
    {
        return 'ticket';
    }
}

Controller/TicketController.php
<?php

namespace Hackzilla\Bundle\TicketBundle\Controller;

use Hackzilla\Bundle\TicketBundle\Event\TicketEvent;
use Hackzilla\Bundle\TicketBundle\Form\Type\TicketMessageType;
use Hackzilla\Bundle\TicketBundle\Form\Type\TicketType;
use Hackzilla\Bundle\TicketBundle\Model\TicketInterface;
use Hackzilla\Bundle\TicketBundle\Model\TicketMessageInterface;
use Hackzilla\Bundle\TicketBundle\TicketEvents;
use Hackzilla\Bundle\TicketBundle\TicketRole;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\HttpFoundation\Request;

/**
 * Ticket controller.
 */
class TicketController extends Controller
{
    /**
     * Lists all Ticket entities.
     *
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction(Request $request)
    {
        $userManager = $this->getUserManager();
        $ticketManager = $this->get('hackzilla_ticket.ticket_manager');

        $ticketState = $request->get('state', $this->get('translator')->trans('STATUS_OPEN'));
        $ticketPriority = $request->get('priority', null);

        $query = $ticketManager->getTicketList(
            $userManager,
            $ticketManager->getTicketStatus($ticketState),
            $ticketManager->getTicketPriority($ticketPriority)
        );

        $pagination = $this->get('knp_paginator')->paginate(
            $query->getQuery(),
            $request->query->get('page', 1)/*page number*/,
            10/*limit per page*/
        );

        return $this->render(
            $this->container->getParameter('hackzilla_ticket.templates')['index'],
            [
                'pagination'     => $pagination,
                'ticketState'    => $ticketState,
                'ticketPriority' => $ticketPriority,
            ]
        );
    }

    /**
     * Creates a new Ticket entity.
     *
     * @param Request $request
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function createAction(Request $request)
    {
        $ticketManager = $this->get('hackzilla_ticket.ticket_manager');

        $ticket = $ticketManager->createTicket();
        $form = $this->createForm(TicketType::class, $ticket);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $message = $ticket->getMessages()->current();
            $message->setStatus(TicketMessageInterface::STATUS_OPEN)
                ->setUser($this->getUserManager()->getCurrentUser());

            $ticketManager->updateTicket($ticket, $message);
            $this->dispatchTicketEvent(TicketEvents::TICKET_CREATE, $ticket);

            return $this->redirect($this->generateUrl('hackzilla_ticket_show', ['ticketId' => $ticket->getId()]));
        }

        return $this->render(
            $this->container->getParameter('hackzilla_ticket.templates')['new'],
            [
                'entity' => $ticket,
                'form'   => $form->createView(),
            ]
        );
    }

    /**
     * Displays a form to create a new Ticket entity.
     */
    public function newAction()
    {
        $ticketManager = $this->get('hackzilla_ticket.ticket_manager');
        $entity = $ticketManager->createTicket();

        $form = $this->createForm(TicketType::class, $entity);

        return $this->render(
            $this->container->getParameter('hackzilla_ticket.templates')['new'],
            [
                'entity' => $entity,
                'form'   => $form->createView(),
            ]
        );
    }

    /**
     * Finds and displays a TicketInterface entity.
     *
     * @param int $ticketId
     *
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function showAction($ticketId)
    {
        $ticketManager = $this->get('hackzilla_ticket.ticket_manager');
        $ticket = $ticketManager->getTicketById($ticketId);

        if (!$ticket) {
            return $this->redirect($this->generateUrl('hackzilla_ticket'));
        }

        $currentUser = $this->getUserManager()->getCurrentUser();
        $this->getUserManager()->hasPermission($currentUser, $ticket);

        $data = ['ticket' => $ticket];

        $message = $ticketManager->createMessage($ticket);

        if (TicketMessageInterface::STATUS_CLOSED != $ticket->getStatus()) {
            $data['form'] = $this->createMessageForm($message)->createView();
        }

        if ($currentUser && $this->getUserManager()->hasRole($currentUser, TicketRole::ADMIN)) {
            $data['delete_form'] = $this->createDeleteForm($ticket->getId())->createView();
        }

        return $this->render($this->container->getParameter('hackzilla_ticket.templates')['show'], $data);
    }

    /**
     * Finds and displays a TicketInterface entity.
     *
     * @param Request $request
     * @param int     $ticketId
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function replyAction(Request $request, $ticketId)
    {
        $ticketManager = $this->get('hackzilla_ticket.ticket_manager');
        $ticket = $ticketManager->getTicketById($ticketId);

        if (!$ticket) {
            throw $this->createNotFoundException($this->get('translator')->trans('ERROR_FIND_TICKET_ENTITY'));
        }

        $user = $this->getUserManager()->getCurrentUser();
        $this->getUserManager()->hasPermission($user, $ticket);

        $message = $ticketManager->createMessage($ticket);

        $form = $this->createMessageForm($message);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $message->setUser($user);
            $ticketManager->updateTicket($ticket, $message);
            $this->dispatchTicketEvent(TicketEvents::TICKET_UPDATE, $ticket);

            return $this->redirect($this->generateUrl('hackzilla_ticket_show', ['ticketId' => $ticket->getId()]));
        }

        $data = ['ticket' => $ticket, 'form' => $form->createView()];

        if ($user && $this->get('hackzilla_ticket.user_manager')->hasRole($user, TicketRole::ADMIN)) {
            $data['delete_form'] = $this->createDeleteForm($ticket->getId())->createView();
        }

        return $this->render($this->container->getParameter('hackzilla_ticket.templates')['show'], $data);
    }

    /**
     * Deletes a Ticket entity.
     *
     * @param Request $request
     * @param int     $ticketId
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction(Request $request, $ticketId)
    {
        $userManager = $this->getUserManager();
        $user = $userManager->getCurrentUser();

        if (!\is_object($user) || !$userManager->hasRole($user, TicketRole::ADMIN)) {
            throw new \Symfony\Component\HttpKernel\Exception\HttpException(403);
        }

        $form = $this->createDeleteForm($ticketId);

        if ($request->isMethod('DELETE')) {
            $form->submit($request->request->get($form->getName()));

            if ($form->isValid()) {
                $ticketManager = $this->get('hackzilla_ticket.ticket_manager');
                $ticket = $ticketManager->getTicketById($ticketId);

                if (!$ticket) {
                    throw $this->createNotFoundException($this->get('translator')->trans('ERROR_FIND_TICKET_ENTITY'));
                }

                $ticketManager->deleteTicket($ticket);
                $this->dispatchTicketEvent(TicketEvents::TICKET_DELETE, $ticket);
            }
        }

        return $this->redirect($this->generateUrl('hackzilla_ticket'));
    }

    private function dispatchTicketEvent($ticketEvent, TicketInterface $ticket)
    {
        $event = new TicketEvent($ticket);
        $this->get('event_dispatcher')->dispatch($ticketEvent, $event);
    }

    /**
     * Creates a form to delete a Ticket entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder(['id' => $id])
            ->add('id', HiddenType::class)
            ->getForm();
    }

    /**
     * @param TicketMessageInterface $message
     *
     * @return \Symfony\Component\Form\Form
     */
    private function createMessageForm(TicketMessageInterface $message)
    {
        $form = $this->createForm(
            TicketMessageType::class,
            $message,
            ['new_ticket' => false]
        );

        return $form;
    }

    /**
     * @return \Hackzilla\Bundle\TicketBundle\Manager\UserManagerInterface
     */
    private function getUserManager()
    {
        $userManager = $this->get('hackzilla_ticket.user_manager');

        return $userManager;
    }
}

Resources/views/Ticket/index.html.twig
{% extends 'HackzillaTicketBundle::layout.html.twig' %}
{% import hackzilla_ticket.templates.macros as macros %}

{% block hackzilla_ticket_content -%}
    <h1>{{ 'HEADING_TICKET_LIST'|trans }}</h1>

    <div class="row">
        <div class="col-xs-4">
            <div class="btn-group">
                <a href="{{ path('hackzilla_ticket', {'state': 'STATUS_OPEN'|trans}) }}"
                   class="btn btn-default {{ ticketState != 'STATUS_CLOSED'|trans ? 'active' : '' }}">{{ 'STATUS_OPEN'|trans|upper }}</a>
                <a href="{{ path('hackzilla_ticket', {'state': 'STATUS_CLOSED'|trans}) }}"
                   class="btn btn-default {{ ticketState == 'STATUS_CLOSED'|trans ? 'active' : '' }}">{{ 'STATUS_CLOSED'|trans|upper }}</a>
            </div>
        </div>

        <div class="col-xs-4 text-center">
            <div class="btn-group">
                <a href="{{ path('hackzilla_ticket') }}"
                   class="btn btn-default {{ ticketPriority is null ? 'active' : '' }}"><span
                            class="glyphicon glyphicon-remove"></span></a>
                <a href="{{ path('hackzilla_ticket', {'priority': 'PRIORITY_HIGH'|trans}) }}"
                   class="btn btn-danger {{ ticketPriority == 'PRIORITY_HIGH'|trans ? 'active' : '' }}">{{ 'PRIORITY_HIGH'|trans|upper }}</a>
                <a href="{{ path('hackzilla_ticket', {'priority': 'PRIORITY_MEDIUM'|trans}) }}"
                   class="btn btn-warning {{ ticketPriority == 'PRIORITY_MEDIUM'|trans ? 'active' : '' }}">{{ 'PRIORITY_MEDIUM'|trans|upper }}</a>
                <a href="{{ path('hackzilla_ticket', {'priority': 'PRIORITY_LOW'|trans}) }}"
                   class="btn btn-info {{ ticketPriority == 'PRIORITY_LOW'|trans ? 'active' : '' }}">{{ 'PRIORITY_LOW'|trans|upper }}</a>
            </div>
        </div>

        <div class="col-xs-4 text-right">
            <div class="btn-group">
                <a href="{{ path('hackzilla_ticket_new') }}" class="btn btn-primary"><span
                            class="glyphicon glyphicon-plus"></span> {{ 'BUTTON_NEW'|trans }}</a>
            </div>
        </div>
    </div>

    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th class="col-xs-1">{{ knp_pagination_sortable(pagination, 'HEADING_TICKET'|trans, 't.id') }}</th>
            <th{% if pagination.isSorted('t.subject') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_SUBJECT'|trans, 't.subject') }}</th>
            <th{% if pagination.isSorted('t.userCreated') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_AUTHOR'|trans, 't.userCreated') }}</th>
            <th{% if pagination.isSorted('t.status') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_STATUS'|trans, 't.status') }}</th>
            <th{% if pagination.isSorted('t.priority') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_PRIORITY'|trans, 't.priority') }}</th>
            <th{% if pagination.isSorted('t.modified') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_MODIFIED'|trans, 't.lastMessage') }}</th>
            <th{% if pagination.isSorted('t.created') %} class="sorted"{% endif %}>{{ knp_pagination_sortable(pagination, 'HEADING_CREATED'|trans, 't.createdAt') }}</th>
        </tr>
        </thead>
        <tbody>
        {% for entity in pagination %}
            <tr>
                <td><a href="{{ path('hackzilla_ticket_show', { 'ticketId': entity.id }) }}">{{ entity.id }}</a></td>
                <td><a href="{{ path('hackzilla_ticket_show', { 'ticketId': entity.id }) }}">{{ entity.subject }}</a></td>
                <td>{{ entity.userCreatedObject }}</td>
                <td>{{ macros.status_btn(entity.status, entity.statusString|trans, true) }}</td>
                <td>{{ macros.priority_btn(entity.priority, entity.priorityString|trans, true) }}</td>
                <td>{% if entity.lastMessage %}{{ entity.lastMessage|date('LABEL_DATE_TIME_FORMAT'|trans) }}{% endif %}</td>
                <td>{% if entity.createdAt %}{{ entity.createdAt|date('LABEL_DATE_TIME_FORMAT'|trans) }}{% endif %}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">{{ 'MESSAGE_NO_TICKETS'|trans }}.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="navigation text-right">
        {{ knp_pagination_render(pagination, 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig') }}
    </div>

{% endblock %}

Resources/views/Ticket/new.html.twig
{% extends 'HackzillaTicketBundle::layout.html.twig' %}

{% block hackzilla_ticket_content -%}
    <h1>{{ 'HEADING_NEW_TICKET'|trans }}</h1>

    <div class="well well-sm">
        {{ form_start(form, {'method': 'POST', 'action': path('hackzilla_ticket_create')}) }}
            <div class="form-group row">
                {{ form_label(form.subject, '', { 'label_attr': {'class': 'col-lg-2 col-md-2 col-sm-2 control-label'} }) }}
                <div class="col-lg-8 col-md-8 col-sm-8">
                    {{ form_widget(form.subject, { 'attr': {'class': 'form-control', 'placeholder': 'LABEL_ENTER_SUBJECT' } }) }}
                    {{ form_errors(form.subject) }}
                </div>
            </div>

            {% if form.messages|length == 0 %}
                {% include hackzilla_ticket.templates.prototype with {'form': form.messages.vars.prototype} %}
            {% else %}
                {% include hackzilla_ticket.templates.prototype with {'form': form.messages.__name__} %}
            {% endif %}

            {{ form_rest(form) }}

            <div class="form-group row">
                <div class="col-lg-offset-2 col-lg-10 col-md-offset-2 col-md-10 col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">{{ 'BUTTON_CREATE'|trans }}</button>

                    <a href="{{ path('hackzilla_ticket') }}" class="btn btn-default">
                        {{ 'BUTTON_BACK_TO_LIST'|trans }}
                    </a>
                </div>
            </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

Resources/views/Ticket/show.html.twig
{% extends 'HackzillaTicketBundle::layout.html.twig' %}
{% import hackzilla_ticket.templates.macros as macros %}

{% block hackzilla_ticket_content -%}

    <p>
        <a href="{{ path('hackzilla_ticket') }}" class="btn btn-default">{{ 'BUTTON_BACK_TO_LIST'|trans }}</a>
    </p>

    <h1>
        {{ macros.status_btn(ticket.status, ticket.statusString|trans) }}
        {{ macros.priority_btn(ticket.priority, ticket.priorityString|trans) }}
        <small>#{{ ticket.id }}</small>
        - {{ ticket.subject }}
    </h1>

    <p>
        <i>{{ 'LABEL_CREATED_BY'|trans }} {{ ticket.userCreatedObject }}
            , {{ ticket.createdAt|date('LABEL_DATE_FORMAT'|trans) }}</i>
        {# <br />{{ 'LABEL_PRIORITY'|trans }} <span class="label label-{{ ticket.priority == 0 ? 'default' : (ticket.priority == 20 ? 'primary' : (ticket.priority == 21 ? 'warning' : 'danger')) }}">{{ ticket.priorityString|trans }}</span> #}
    </p>


    {# <h3>{{ 'HEADING_TICKET_THREAD'|trans }}</h3> #}
    {% set previousStatus = null %}
    {% set previousPriority = null %}

    {% for message in ticket.messages %}

        {% if previousStatus and previousStatus != message.status %}
            {{ macros.status_alert(message.status, message.statusString|trans) }}
        {% endif %}

        {% if previousPriority and previousPriority != message.priority %}
            {{ macros.priority_alert(message.priority, message.priorityString|trans) }}
        {% endif %}

        {% if message.message|length > 0 %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    {{ message.userObject }}
                    {# <br />{{ 'LABEL_PRIORITY'|trans }} <span class="label label-{{ message.priority == 0 ? 'default' : (message.priority == 20 ? 'primary' : (message.priority == 21 ? 'warning' : 'danger')) }}">{{ message.priorityString|trans }}</span> #}
                    {# <br />{{ 'LABEL_STATUS'|trans }} <span class="label label-{{ message.status ? 'success' : 'danger' }}">{{ message.statusString|trans }}</span> #}

                    <span class="pull-right">
                {% if message.userObject != ticket.userCreatedObject %}<span
                        class="label label-danger">{{ 'LABEL_ADMIN'|trans }}</span> {% endif %}
                        <small><i>{{ message.createdAt|date('LABEL_DATE_TIME_FORMAT'|trans) }}</i></small>
            </span>
                </div>
                <div class="panel-body">
                    {{ message.message|nl2br }}
                    {% if(hasTicketFeature('attachment')) %}
                        {{ include('@HackzillaTicket/Ticket/show_attachment.html.twig', {'message': message}) }}
                    {% endif %}
                </div>
            </div>
        {% endif %}

        {% set previousStatus = message.status %}
        {% set previousPriority = message.priority %}
    {% endfor %}

    <hr />

    {% if form is defined %}
        <div class="well well-sm">
            {{ form_start(form, {'method': 'POST', 'action': path('hackzilla_ticket_reply', {'ticketId': ticket.id})}) }}
            {% include hackzilla_ticket.templates.prototype with {'form': form} %}

            {{ form_rest(form) }}

            <p class="form_actions">
                <button type="submit" class="btn btn-primary">{{ 'BUTTON_UPDATE'|trans }}</button>
            </p>
            {{ form_end(form) }}
        </div>
    {% endif %}

    {% if delete_form is defined %}
        {{ form_start(delete_form, {'method': 'POST', 'action': path('hackzilla_ticket_delete', {'ticketId': ticket.id}), 'attr': {'class': 'text-right'}}) }}
        <input type="hidden" name="_method" value="DELETE"/>
        {{ form_widget(delete_form) }}

        <button type="submit" class="btn btn-danger">{{ 'BUTTON_DELETE'|trans }}</button>
        {{ form_end(delete_form) }}
    {% endif %}

{% endblock %}

Resources/views/Ticket/show_attachment.html.twig
{% import hackzilla_ticket.templates.macros as macros %}
{% if message.attachmentName %}
<br>
<div class="ticket_attachment">
    <span class="glyphicon glyphicon-paperclip"></span>
    <a href="{{ path('hackzilla_ticket_attachment', {ticketMessageId: message.id}) }}">{{ message.attachmentName }}</a>
    {% if message.attachmentSize is not null %}{{ macros.bytesToSize(message.attachmentSize) }}{% endif %}
</div>
{% endif %}